# Generated by Django 4.2.4 on 2024-01-25 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=100, unique=True)),
                ('cliente', models.CharField(max_length=30)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('fecha_entrega_esperada', models.DateField()),
                ('total_orden', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESO', 'En proceso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('direccion_envio', models.CharField(blank=True, max_length=255)),
                ('metodo_envio', models.CharField(blank=True, max_length=100)),
                ('direccion_facturacion', models.CharField(blank=True, max_length=255)),
                ('informacion_pago', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_en_stock', models.IntegerField(default=0)),
                ('codigo_producto', models.CharField(max_length=50, unique=True)),
                ('fecha_modificacion', models.DateField(auto_now=True)),
                ('ancho', models.IntegerField(default=0)),
                ('alto', models.IntegerField(default=0)),
                ('largo', models.IntegerField(default=0)),
                ('diametro', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Pedidos',
        ),
        migrations.AddField(
            model_name='itemorden',
            name='orden_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gestion.ordencompra'),
        ),
        migrations.AddField(
            model_name='itemorden',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.producto'),
        ),
    ]
