# Generated by Django 4.2.4 on 2024-01-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_itemorden_ordencompra_producto_delete_pedidos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='largo',
            field=models.FloatField(default=0),
        ),
    ]
