# Generated by Django 4.2.4 on 2024-01-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_alter_producto_largo'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorden',
            name='prioridad',
            field=models.BooleanField(default=False),
        ),
    ]
