# Generated by Django 4.2.4 on 2024-01-26 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_remove_ordencompra_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorden',
            name='cantidad_producida',
            field=models.IntegerField(default=0),
        ),
    ]
