# Generated by Django 4.2.4 on 2024-02-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_itemorden_cantidad_producida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='tipo',
            field=models.CharField(choices=[('cambio_rollo', 'Cambio de Rollo'), ('despacho', 'Despacho'), ('ingreso_material', 'Ingreso de Material'), ('pana_mantencion', 'Pana o Mantención'), ('produccion', 'Producción'), ('setup_ajustes', 'Setup o Ajustes')], max_length=30),
        ),
    ]
