# Generated by Django 4.2.4 on 2024-02-05 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_alter_produccion_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produccion',
            name='duracion_produccion',
        ),
        migrations.RemoveField(
            model_name='produccion',
            name='produccion_por_hora',
        ),
        migrations.AddField(
            model_name='produccion',
            name='en_curso',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='hora_inicio',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 2, 5, 19, 15, 37, 131577, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='hora_termino',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 2, 5, 19, 15, 37, 131577, tzinfo=datetime.timezone.utc)),
        ),
    ]
