# Generated by Django 4.2.4 on 2024-02-12 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_remove_produccion_duracion_produccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='hora_inicio',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 2, 12, 11, 28, 37, 149370)),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='hora_termino',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 2, 12, 11, 28, 37, 149370)),
        ),
    ]
