# Generated by Django 4.2.4 on 2024-03-01 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_alter_produccion_hora_inicio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='hora_inicio',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 3, 1, 13, 29, 35, 172956)),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='hora_termino',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 3, 1, 13, 29, 35, 172956)),
        ),
    ]
