# Generated by Django 4.2.4 on 2024-03-05 11:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_alter_produccion_hora_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemorden',
            name='revisado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='hora_inicio',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 3, 5, 11, 38, 30, 395086)),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='hora_termino',
            field=models.TimeField(verbose_name=datetime.datetime(2024, 3, 5, 11, 38, 30, 395086)),
        ),
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('numero_secuencia', models.IntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.producto')),
            ],
            options={
                'ordering': ['cantidad'],
            },
        ),
    ]
