# Generated by Django 5.0.7 on 2024-07-13 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_itemorden_revisado_alter_produccion_hora_inicio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordenproduccion',
            options={'ordering': ['numero_secuencia', '-cantidad']},
        ),
        migrations.AddField(
            model_name='producto',
            name='peso',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='hora_inicio',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='hora_termino',
            field=models.TimeField(),
        ),
    ]
